### ISSUE TITLE
Delay persists between lines of dialogue.

### ISSUE THREAD

**Issue by JonathanGorr** [redbluegames/unity-text-typer#5]
The text typer doesn't reset the text speed on a new line. The bug occurs when you skip dialogue between delay tags. I fixed this temporarily by prefacing each new line with its own delay:

`scripts.Enqueue("<delay=0></delay>" + conversationText);`

**Comment by edwardrowe** [comment]
I'm at GDC this week so I'm likely not going to be able to look at this until next week. Thanks for the bug report, though.

I'm having a bit of trouble understanding quite what the bug is. Every opening delay tag should require a closing tag within the printing text. What do the calls the bugged calls that you are making to a TextTyper component look like?

**Comment by edwardrowe** [comment]
Ah I see what you mean now. If you skip or print new text while the Delay tag is active in the print, it will not restore the delay.

**Comment by edwardrowe** [comment]
Should be fixed in latest release (v1.2). You may need to delete the old plugin before installing the new one. Unity doesn't seem to like when files are renamed...

**Comment by JonathanGorr** [comment]
Sorry buddy. I don't get email notifications apparently for github. I was at GDC too funnily enough. Thanks for fixing it. Great plugin!

**Comment by edwardrowe** [comment]
No problem! Thanks for the bug report.
